[package]
name = "bevy_physx"
version = "0.0.1"
authors = ["Alex Kocharin <alex@kocharin.ru>"]
description = "PhysX plugin for Bevy"
readme = "README.md"
license = "MIT"
edition = "2021"

[lib]
name = "bevy_physx"
path = "src/lib.rs"

[dependencies]
bevy = "0.10.0"
derive_more = "0.99.17"
enumflags2 = "0.7.5"
#physx = "0.16.0"
physx = { path = "src/physx" }
physx-sys = "0.8.1"

[dev-dependencies]
bevy-inspector-egui = "0.18.1"
bevy_infinite_grid = { git = "https://github.com/PikminGuts92/bevy_infinite_grid", rev = "ee7f83f" }
