[package]
name = "bevy_physx"
version = "0.0.1"
authors = ["Alex Kocharin <alex@kocharin.ru>"]
description = "PhysX plugin for Bevy"
readme = "README.md"
license = "MIT"
edition = "2021"

[lib]
name = "bevy_physx"
path = "src/lib.rs"

[dependencies]
bevy = "0.10.0"
derive_more = "0.99.17"
enumflags2 = "0.7.5"
physx = { git = "https://github.com/rlidwka/physx-rs", branch = "mesh_methods" }
physx-sys = { git = "https://github.com/rlidwka/physx-rs", branch = "mesh_methods" }

[dev-dependencies]
bevy-inspector-egui = "0.18.1"
